### ISSUE TITLE
More complex epidemiological model examples?

### ISSUE THREAD

**Issue by robertfeldt** [sdwfrost/Gillespie.jl#17]
Has anyone implemented or seen any SEID or SEIVD models as SDE's or for Gillespie?

Any hints welcome.

**Comment by sdwfrost** [comment]
Apologies - I haven't looked at my repo for months. Please take a look at [https://github.com/epirecipes/sir-julia](https://github.com/epirecipes/sir-julia) for a fairly broad set of SIR type models in Julia.
