### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by rsrock** [sdwfrost/Gillespie.jl#5]
I saw your tweet that this package now has a publication associated with it (congrats!).  Could you provide the citation here?  I have a couple of manuscripts to submit where we used your package, and I'd like to be the first to cite you.

Thanks for the great work here!

**Comment by sdwfrost** [comment]
I have updated the README to include a citation and a link to a bibtex entry. Thanks for your support! The released version is much faster than previous commits, so I'd recommend giving it a try. Feature requests welcome too.
