### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by ararslan** [sdwfrost/Gillespie.jl#8]
It looks like the PkgEvaluator tests are failing for Gillespie.jl on both Julia 0.4 and 0.5. Since the Travis tests on master are currently passing, tagging a new release of the package should do the trick, I would think.

As an aside, it may be a good idea to include the PkgEval badges in the README. They can be found for this package at http://pkg.julialang.org/detail/Gillespie.html.

Thanks!

**Comment by sdwfrost** [comment]
Thanks @ararslan - I've tagged a new release. Waiting until PkgEval runs to see if that fixes things. The badges are now in README.

**Comment by ararslan** [comment]
For PkgEval to see the new release, you'll have to submit a pull request to METADATA.jl that includes the change. Typically this can be done all at once (tagging and submitting the PR) using the PkgDev package on Julia 0.5 or the `Pkg` functions from Base on 0.4. For example, you can do all of this from the Julia REPL as follows (in this example using 0.5):
```julia
Pkg.add("PkgDev") # assuming you don't already have it
Pkg.update()
using PkgDev
PkgDev.tag("Gillespie", :patch)
PkgDev.publish()
```
This approach is much, much easier and less error prone than constructing and submitting the METADATA.jl PR manually. However, I should note that if you want the next installable version to be 0.0.2, you'll first have to delete the tag from the repo here, otherwise `PkgDev.tag` will get upset that the v0.0.2 tag already exists.

Let me know if you have any questions—I know this can get complicated!

**Comment by sdwfrost** [comment]
Dear @ararslan 

After a false start or two, a new release is tagged, and now the packages passes. Thanks for the help. Now on to more features!

**Comment by ararslan** [comment]
Fantastic! 🎉
